/**
 * Czech lang variables 
 * encoding: utf-8
 *  
 * @author Michi
 *  
 * $Id: cs.js,v 1.12 2006/02/23 13:02:37 spocke Exp $ 
 */  

tinyMCE.addToLang('table',{
general_tab : 'Obecné',
advanced_tab : 'Pokroèilé',
general_props : 'Obecné vlastnosti',
advanced_props : 'Pokroèilé vlastnosti',
desc : 'Vložit novou tabulku',
row_before_desc : 'Vložit øádek pøed',
row_after_desc : 'Vložit øádek za',
delete_row_desc : 'Smazat øádek',
col_before_desc : 'Vložit sloupec pøed',
col_after_desc : 'VLožit sloupec za',
delete_col_desc : 'Smazat sloupec',
rowtype : 'Øádek v tabulce',
title : 'Vložit/Modifikovat tabulku',
width : 'Šíøka',
height : 'Výška',
cols : 'Sloupce',
rows : 'Øádky',
cellspacing : 'Mezera mezi buòkami',
cellpadding : 'Výplò bunìk',
border : 'Rámeèek',
align : 'Zarovnání',
align_default : 'Automatické',
align_left : 'Vlevo',
align_right : 'Vpravo',
align_middle : 'Na støed',
row_title : 'Vlastnosti øádku',
cell_title : 'Vlastnosti buòky',
cell_type : 'Typ buòky',
row_desc : 'Vlastnosti øádku',
cell_desc : 'Vlastnosti buòky',
valign : 'Vertikální zarovnání',
align_top : 'Nahoru',
align_bottom : 'Dolù',
props_desc : 'Vlastnosti tabulky',
bordercolor : 'Barva rámeèku',
bgcolor : 'Barva pozadí',
merge_cells_title : 'Slouèit buòky',
split_cells_desc : 'Rozdìlit buòky',
merge_cells_desc : 'Slouèit buòky',
cut_row_desc : 'Vyjmout øádek',
copy_row_desc : 'Kopírovat øádek',
paste_row_before_desc : 'Vložit øádek pøed',
paste_row_after_desc : 'Vložit øádek za',
id : 'Id',
style: 'Styl',
langdir : 'Smìr textu',
langcode : 'Kód jazyka',
mime : 'Cílový MIME typ',
ltr : 'Z leva doprava',
rtl : 'Z prava doleva',
bgimage : 'Obrázek pozadí',
summary : 'Obsah',
td : "Data",
th : "Hlavièka",
cell_cell : 'Aktualizovat souèasnou buòku',
cell_row : 'Aktualizovat všechny buòky v øádku',
cell_all : 'Aktualizovat všechny buòky v tabulce',
row_row : 'Aktualizovat souèasný øádek',
row_odd : 'Aktualizovat liché øádky tabulky',
row_even : 'Aktualizovat sudé øádky v tabulce',
row_all : 'Aktualizovat všechny øádky v tabulce',
thead : 'Hlavièka tabulky',
tbody : 'Tìlo tabulky',
tfoot : 'Patièka tabulky',
del : 'Smazat tabulku',
scope : 'Scope',
row : 'Øádek',
col : 'Sloupec',
rowgroup : 'Skupina øádkù',
colgroup : 'Skupina sloupcù',
missing_scope: 'Jste si jistý(á), že chcete pokraèovat bez vyplnìní rozsahu pro tuto buòku tabulky? Bez nìj mùže být težké handicapovaným uživatelùm porozumìt obsahu nebo datùm obsažených v tabulce.'
});
